//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentaPrestamo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDDEFEXTEntities : DbContext
    {
        public BDDEFEXTEntities()
            : base("name=BDDEFEXTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<DerechoLinea> DerechoLinea { get; set; }
        public virtual DbSet<Devolucion> Devolucion { get; set; }
        public virtual DbSet<Interno> Interno { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Prestamo> Prestamo { get; set; }
        public virtual DbSet<Repuesto> Repuesto { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TipoRepuesto> TipoRepuesto { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<ChoferDerLin> ChoferDerLin { get; set; }
        public virtual DbSet<DetalleDevolucion> DetalleDevolucion { get; set; }
        public virtual DbSet<DetallePrestamo> DetallePrestamo { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<RolesPersonal> RolesPersonal { get; set; }
        public virtual DbSet<View_Report1> View_Report1 { get; set; }
        public virtual DbSet<View_Report2> View_Report2 { get; set; }
        public virtual DbSet<View_Report3> View_Report3 { get; set; }
        public virtual DbSet<View_Report4> View_Report4 { get; set; }
        public virtual DbSet<SistemaVentaPrestamo.Models.OrdenRepuesto> OrdenRepuesto { get; set; }

        public virtual int SPBackupDiferencial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBackupDiferencial");
        }
    
        public virtual int SPBackupTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPBackupTotal");
        }
    }
}
