//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentaPrestamo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int idBit { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Terminal { get; set; }
        public string Usuario { get; set; }
        public string Aplicacion { get; set; }
    }
}
