//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentaPrestamo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucion()
        {
            this.DetalleDevolucion = new HashSet<DetalleDevolucion>();
        }
    
        public int idDevolucion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idPrestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevolucion> DetalleDevolucion { get; set; }
    }
}
