//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentaPrestamo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interno
    {
        public int idInterno { get; set; }
        public string Chasis { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public int idDerechoLinea { get; set; }
    
        public virtual DerechoLinea DerechoLinea { get; set; }
    }
}
